#!/bin/sh 
export LOCAL=/projects/codes/equilibrium/efit++/efit++Data/netCDF/development/local
export CPLUS_INCLUDE_PATH=$LOCAL/include
export LIBRARY_PATH=$LOCAL/lib
export LD_LIBRARY_PATH=$LIBRARY_PATH":"$LD_LIBRARY_PATH
# generate c-code
./ncgen4  $1
