image: Visual Studio 2017

environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      MINGW_INSTALL_LOCN: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
      MINGW_BIN_LOCN: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\msys64\usr\bin
      CMAKE_GENERATOR: "Visual Studio 15 Win64"


platform:
    - x64

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

install:
  - cmd: set PATH=%PATH%:%MINGW_BIN_LOCN%
  - cmd: dir %MINGW_INSTALL_LOCN%
  - cmd: dir %MINGW_BIN_LOCN%
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - cmd: conda update conda
  - cmd: conda install hdf5 curl hdf4
  - cmd: m4 --help

configuration: Release

build: off

# Run a custom script.
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release
  - cmd: if errorlevel 1 exit 1
  - cmd: cmake --build . --config Release --target netcdf
