image: Visual Studio 2017

environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

platform:
    - x64

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - cmd: conda update conda
  - cmd: conda install hdf5 curl hdf4
  - cmd: dir

configuration: Release

build: off

build:
  parallel: true


# Run a custom script.
build_script:
  - cmd: mkdir %SRC_DIR%\build
  - cmd: cd %SRC_DIR%\build
  - cmd: cmake .. -G "Visual Studio 15 Win64" -DCMAKE_BUILD_TYPE=Release %SRC_DIR%
  - cmd: if errorlevel 1 exit 1
  - cmd: cmake --build . --config Release --target netcdf
