image: Visual Studio 2017

environment:
  matrix:
    - TARGET_ARCH: x64

platform:
    - x64

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - cmd: conda update conda
