# CTest/CDash configuration

IF(USE_REMOTE_CDASH)
	set(CTEST_PROJECT_NAME "netcdf-c")
	set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
	set(CTEST_SITE "Unidata OSX")
	set(CTEST_DROP_METHOD "http")
	set(CTEST_DROP_SITE "my.cdash.org")
	set(CTEST_DROP_LOCATION "/submit.php?project=netcdf-c")
	set(CTEST_DROP_SITE_CDASH TRUE)
ELSEIF(BUILDING_TRUNK)
	SET (CTEST_DROP_METHOD "http")
	SET (CTEST_DROP_SITE "yakov.unidata.ucar.edu/")
	SET (CTEST_DROP_LOCATION "CDash/submit.php?project=netcdf-c")
	SET (CTEST_DROP_SITE_CDASH TRUE)
ELSEIF(WORKING_FROM_HOME)
	SET (CTEST_DROP_METHOD "http")
	SET (CTEST_DROP_SITE "localhost:4111/")
	SET (CTEST_DROP_LOCATION "CDash/submit.php?project=netcdf-cmake")
	SET (CTEST_DROP_SITE_CDASH TRUE)
ELSE()
	SET (CTEST_PROJECT_NAME "netcdf-cmake")
	SET (CTEST_DROP_METHOD "http")
	SET (CTEST_DROP_SITE "yakov.unidata.ucar.edu/")
	SET (CTEST_DROP_LOCATION "CDash/submit.php?project=netcdf-cmake")
	SET (CTEST_DROP_SITE_CDASH TRUE)
ENDIF()
