#!/bin/bash

JNADIR="c:/opt/jna"

PREFIX="c:/opt"

CPP="${JNADIR}/deps/shared"

FLAGS=""

FLAGS="-DCMAKE_INSTALL_PREFIX=${PREFIX} ${FLAGS}"
FLAGS="-DCMAKE_PREFIX_PATH=${CPP} ${FLAGS}"

FLAGS="-DHDF5_DIR=${CPP}/cmake/hdf5 ${FLAGS}"

FLAGS="-DENABLE_CONVERSION_WARNINGS=OFF ${FLAGS}"
FLAGS="-DBUILD_UTILITIES=OFF ${FLAGS}"
FLAGS="-DENABLE_EXAMPLES=OFF ${FLAGS}"

rm -fr ./build
mkdir build
pushd build
cmake -G"Visual Studio 10" ${FLAGS} ..
cmake --build . --config Release
cmake --build . --target INSTALL
popd

exit
