#!/bin/sh 
export LOCAL=/home/lynton/local
export CPLUS_INCLUDE_PATH=$LOCAL/include
export C_INCLUDE_PATH=$LOCAL/include
export LIBRARY_PATH=$LOCAL/lib

export CPLUS_INCLUDE_PATH=$LOCAL/include:/usr/local/fusion/netcdf-4/include
export C_INCLUDE_PATH=$LOCAL/include:/usr/local/fusion/netcdf-4/include
export LIBRARY_PATH=$LOCAL/lib:/usr/local/fusion/netcdf-4/lib
#g++ -g  test_group.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#g++ -g  test_dim.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#g++ -g  test_att.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#g++ -g  test_var.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#g++ -g  test_var2.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
g++ -g  test_type.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#g++ -g  test_type4.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#gcc -g  test_type4.c  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#gcc -g  test_type4.c  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include



#g++ -g  test_type2.cpp  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include
#gcc -g  test_type2.c  -lnetcdf_c++4  -lnetcdf -lhdf5_hl -lhdf5 -lz  -I include



#NcFile:: should enums be inside or outside class defintion?