#!/bin/sh
export LOCAL=/home/lynton/local
export LD_LIBRARY_PATH=$LOCAL/lib:/usr/local/fusion/netcdf-4/lib
case "$#"  in
    0)
        a.out;;
#    ~/local/bin/valgrind   --tool=memcheck a.out ;;
    1)  
	$1 a.out;;
esac
