#!/usr/bin/perl

# Initialize
use strict;
use File::Copy;

our $debug=1;

# Establish environment
# vsdir is dir in which the vs files must execute
our $vsdir=$0;
$vsdir=~s|(.*)/[^/][^/]*|$1|;
if ($debug > 0) {print "vsdir=$vsdir\n";}

# topdir is top src dir of the netcdf installation
# Assume vsdir == $topdir/win32/NET
our $topdir=$vsdir;
$topdir=~s|(.*)/win32/NET|$1|;
if ($debug > 0) {print "topdir=$topdir\n";}

#Load utilities
require "$vsdir/vsutil";
require "$vsdir/vsbuild";

our $cmd="";
our $project="";
our $absdir="";
our $reldir="";
our $sources="";
our @srclist=();
our $usenetcdf4=0;
our $usedap=0;

# Constants
our $hdf5libs="hdf5_hldll.lib hdf5dll.lib zlib1.lib";
our $curllibs="?";

# Known projects
# Mapping of projects to specific win32/NET directories
our %projectmap=(
"netcdf"            => "libsrc",
"ncgen"             => "ncgen",
"ncgen3"            => "ncgen3",
"ncdump"            => "ncdump",
"nccopy"            => "nccopy",
"nctest"            => "nctest",
"nc_test"           => "nc_test",
"tst_netcdf"        => "examples",
"quick_large_files" => "nc_test",
"large_files"       => "nc_test"
);

# Define known projects (i.e. instances of $project.vcproj) by extraction from projectmap
our @projects=keys %projectmap;

# Mapping of projects to UIDS (from netcdf.sln)
our %uidmap=(
"netcdf"           => "1544CEA3-1365-4482-A719-FF5C14BBAE29",
"nctest"            => "16F8E55F-8CFB-412F-80F0-DEBDEAE068A4",
"nc_test"           => "849B73F3-0E32-49AA-993E-01AB112F5BF2",
"ncdump"            => "DA7A6115-385C-44AC-B436-E94E95DDCEAC",
"nccopy"            => "5CDC0F9C-DCC3-4BD3-878C-F71B5FD57F5F",
"ncgen"             => "81623E8F-4575-429E-9EA1-BFFAC1E253F7",
"tst_netcdf"        => "E1F00190-5DE7-4333-9AB9-E4EBB9EB6139",
"large_files"       => "9CF427FE-618D-4E27-9610-937A7E0A7524",
"quick_large_files" => "797D6E0A-0320-41DE-A092-BD562CB88176"
);

#define arguments
$cmd=$ARGV[0];
if($cmd eq "add") {
    $project=$ARGV[1];
    $absdir=$ARGV[2];
    $reldir=$ARGV[3];
    $sources=$ARGV[4];
} elsif($cmd eq "build") {
    $usenetcdf4=$ARGV[1];   
    $usedap=$ARGV[2];
}

#fixups
if ($reldir eq  "") {$reldir=".";}

$sources=trim($sources);
@srclist=split(/[\t ]+/, $sources);

if($debug > 0 && $cmd eq "start") {
    my $key;
    print "projects=@projects\n";
    print "projectmap:\n";
    foreach $key (@projects) {
	print "\t$key => " . $projectmap{$key} . "\n";
    }
}
if ($debug > 1) {
    print "cmd=$cmd\n";
    print "project=$project\n";
    print "absdir=$absdir\n";
    print "reldir=$reldir\n";
    print "srclist=@srclist\n";
    print "usenetcdf4=$usenetcdf4\n";
    print "usedap=$usedap\n";
}

# MAIN
if($cmd eq "start") {
    my $m;
    foreach $m (@projects) {
	my $file="$vsdir/$m.filelist";
	if($debug > 1) {print "file=$file\n";}
	# delete project files
	unlink "$file" || next;
    }
} elsif($cmd eq "add") {
    # compute the directory basepath: assume $absdir == $topdir/$basepath
    my $basepath = $absdir;
    $basepath =~ s@$topdir/(.*)@$1@;
    if($debug > 0) {print "basepath=$basepath\n";}
    if(! -e "$vsdir/$project.filelist" ) {
        open MODFILE, "+>$vsdir/$project.filelist" or die $!;
    } else {
        open MODFILE, ">>$vsdir/$project.filelist" or die $!;
    }
    # append basepath relatvie file names to $project.filelist
    foreach (@srclist) {
	print MODFILE "$basepath/$_\n";
    }
    close MODFILE ;
} elsif($cmd eq "build") {
    build();
    install();
    clean();
} elsif($cmd eq "clean") {
    clean();
} elsif($cmd eq "install") {
    install();
} else {print "unknown command: $cmd\n";}

exit


