#!/usr/bin/perl

# Initialize
use strict;
use File::Copy;

our $debug=1;

# Establish environment
# vsdir is dir in which the vs files must execute
our $vsdir=$0;
$vsdir=~s|(.*)/[^/][^/]*|$1|;
if ($debug > 0) {print "vsdir=$vsdir\n";}

# topdir is top src dir of the netcdf installation
# Assume vsdir == $topdir/win32/NET
our $topdir=$vsdir;
$topdir=~s|(.*)/win32/NET|$1|;
if ($debug > 0) {print "topdir=$topdir\n";}

#Load utilities
require "$vsdir/vsutil";
require "$vsdir/vsbuild";

####################
# Constants

# Constants
our $hdf5libs="hdf5_hldll.lib hdf5dll.lib zlib1.lib";
our $curllibs="?";

# Define known projects (i.e. instances of $project.vcproj)
# Note that examples, fortran, and netcdf_vd
# are not included because they never change.

our @projects=("netcdf","ncgen","ncgen3","ncdump","nccopy",
               "nctest","nc_test","quick_large_files","large_files");

# Known projects
# Mapping of projects to specific win32/NET directories
our %projectmap=(
"netcdf"            => "libsrc",
"ncgen"             => "ncgen",
"ncgen3"            => "ncgen3",
"ncdump"            => "ncdump",
"nccopy"            => "ncdump",
"nctest"            => "nctest",
"nc_test"           => "nc_test",
"quick_large_files" => "nc_test",
"large_files"       => "nc_test"
);

####################

our $cmd="";
our $project="";
our $absdir="";
our $reldir="";
our $sources="";
our @srclist=();
our $usenetcdf4=0;
our $usedap=0;

#define arguments
$cmd=$ARGV[0];
if($cmd eq "add") {
    $project=$ARGV[1];
    $absdir=$ARGV[2];
    $reldir=$ARGV[3];
    $sources=$ARGV[4];
} elsif($cmd eq "build") {
    $usenetcdf4=$ARGV[1];   
    $usedap=$ARGV[2];
}

#fixups
if ($reldir eq  "") {$reldir=".";}

$sources=trim($sources);
@srclist=split(/[\t ]+/, $sources);

if($debug > 0 && $cmd eq "start") {
    my $key;
    print "projects=@projects\n";
    print "projectmap:\n";
    foreach $key (@projects) {
	print "\t$key => " . $projectmap{$key} . "\n" || die "$key";
    }
}
if ($debug > 1) {
    print "cmd=$cmd\n";
    print "project=$project\n";
    print "absdir=$absdir\n";
    print "reldir=$reldir\n";
    print "srclist=@srclist\n";
    print "usenetcdf4=$usenetcdf4\n";
    print "usedap=$usedap\n";
}

# MAIN
if($cmd eq "start") {
    my $m;
    foreach $m (@projects) {
	my $file="$vsdir/$m.filelist";
	if($debug > 1) {print "file=$file\n";}
	# delete project files
	unlink "$file" || next;
    }
} elsif($cmd eq "add") {
    # compute the directory basepath: assume $absdir == $topdir/$basepath
    my $basepath = $absdir;
    $basepath =~ s@$topdir/(.*)@$1@;
    if($debug > 0) {print "basepath=$basepath\n";}
    if(! -e "$vsdir/$project.filelist" ) {
        open MODFILE, "+>$vsdir/$project.filelist" or die $!;
    } else {
        open MODFILE, ">>$vsdir/$project.filelist" or die $!;
    }
    # append basepath relatvie file names to $project.filelist
    foreach (@srclist) {
	print MODFILE "$basepath/$_\n";
    }
    close MODFILE ;
} elsif($cmd eq "build") {
    build();
    install();
    clean();
} elsif($cmd eq "clean") {
    clean();
} elsif($cmd eq "install") {
    install();
} else {print "unknown command: $cmd\n";}

exit


