#!/bin/sh

# Perl trim function to remove whitespace from the start and end of the string
sub trim($)
{
    my $string = shift;
    $string =~ s/^\s+//;
    $string =~ s/\s+$//;
    return $string;
}
# Left trim function to remove leading whitespace
sub ltrim($)
{
    my $string = shift;
    $string =~ s/^\s+//;
    return $string;
}
# Right trim function to remove trailing whitespace
sub rtrim($)
{
    my $string = shift;
    $string =~ s/\s+$//;
    return $string;
}

sub copyfile {
  ($fromfile, $tofile)=@_;
  open TO, "+>$tofile" || die $tofile;
  open FROM, "<$fromfile" || die $fromfile;
  while(<FROM>) {print TO $_ ;}
  close TO;
  close FROM;
}

sub appendfile {
  ($fromfile, $tofile)=@_;
  open TO, ">>$tofile" || die $tofile;
  open FROM, "<$fromfile" || die $fromfile;
  while(<FROM>) {print TO $_ ;}
  close TO;
  close FROM;
}

sub appendtext {
  ($text, $tofile)=@_;
  open TO, ">>$tofile" || die $tofile;
  print TO "$text" ;
  close TO;
}

# Remove duplicates from array keeping relative order
sub uniq {
    my $file;
    my %tmp = ();
    my @uniqlist = ();
    foreach $file (@_) {
	if(exists $tmp{$file}) {next;}
	push(@uniqlist,$file);	
	$tmp{$file} = "";
    }
    return @uniqlist;
}

sub clean {
    foreach $module (@modules) {
	print "deleting: $module.filelist\n";
        unlink "$vsdir/$module.filelist";
	print "deleting: $module.vcproj\n";
        unlink "$vsdir/$module.vcproj";
    }
    # also remove
    print "deleting: global.filelist\n";
    unlink "$vsdir/global.filelist";
}

sub install {
    foreach $module (@modules) {
	my $target = $modulemap{$module};
	if(-e "$vsdir/$module.vcproj") {
   	    print "installing: $vsdir/$module.vcproj => $vsdir/$target/$module.vcproj\n";
	    copy("$vsdir/$module.vcproj","$vsdir/$target/$module.vcproj");
	}
    }
}

1;
