name: Code Style checks
on: [pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run code-style check on changes
        run: git clang-format-18 --diff ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }}
